// generate-all-in-one.mjs
import fs from 'fs';
import path from 'path';
import sharp from 'sharp';

const args = process.argv.slice(2);
const inputFolder = args[0] || './sample';
const outputFile = args[1] || './colormaps/all-colormaps.ts';

const outputDir = path.dirname(outputFile);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

async function generateAllInOne() {
  const files = fs.readdirSync(inputFolder)
    .filter(file => /\.png$/i.test(file))
    .sort();

  const colormaps = [];

  for (const filename of files) {
    const inputPath = path.join(inputFolder, filename);

    try {
      const data = await sharp(inputPath)
        .extract({ left: 0, top: 8, width: 256, height: 1 }) 
        .raw()
        .toBuffer();

      const red = [];
      const green = [];
      const blue = [];

      for (let i = 0; i < data.length; i += 3) {
        red.push(data[i]);
        green.push(data[i + 1]);
        blue.push(data[i + 2]);
      }

      const id = path.basename(filename, '.png')
        .replace(/[^a-zA-Z0-9_]/g, '_')
        .replace(/^_+|_+$/g, '');

      if (!id) continue;

      const title = path.basename(filename, '.png')
        .replace(/_/g, ' ')
        .replace(/^\w/, c => c.toUpperCase()) 
        .trim();

      colormaps.push({
        id,
        title,
        red,
        green,
        blue
      });

      console.log(`✓ ${id} — ${title}`);

    } catch (err) {
      console.error(`error - ${filename}:`, err.message);
    }
  }

  const tsContent = `// Generated colormap array - ${colormaps.length} items
// Auto-generated by generate-all-in-one.mjs

export type Colormap = {
  readonly id: string;
  readonly title: string;
  readonly red: readonly number[];
  readonly green: readonly number[];
  readonly blue: readonly number[];
};

export const colormaps = [
${colormaps.map(cm => `  {
    id: '${cm.id}',
    title: '${cm.title}',
    red: [${cm.red.join(', ')}],
    green: [${cm.green.join(', ')}],
    blue: [${cm.blue.join(', ')}]
  }`).join(',\n')}
] as const;

export default colormaps;
`;

  fs.writeFileSync(outputFile, tsContent, 'utf-8');


}

generateAllInOne();